### ISSUE TITLE
Can't compile the steel-pty dylib

### ISSUE THREAD

**Issue by jonas-w** [mattwparas/helix-config#2] opened 2024-06-25 23:16 UTC
After trying to set everything up (see my journey in the helix issue) It's still not possible to use your configuration with the latest version of your helix fork.

I've also followed the things you pointed out in #1 which brought me a bit further, but when compiling the `steel-pty` crate I get the following error. 
Is this an issue in another crate, or something in my setup?

```console
steel dylib
Attempting to install: "steel-pty"
   Compiling polling v3.6.0
   Compiling tempfile v3.10.1
   Compiling mlua-sys v0.5.1
   Compiling num-rational v0.4.1
   Compiling libssh2-sys v0.3.0
   Compiling libssh-rs-sys v0.2.2
   Compiling lasso v0.7.2
   Compiling abi_stable v0.11.3
   Compiling async_ossl v0.1.0 (https://github.com/mattwparas/wezterm.git?branch=mwp-public-scroll#e1975e65)
   Compiling which v4.4.2
   Compiling toml v0.8.12
   Compiling mlua v0.9.6
   Compiling ssh2 v0.9.4
   Compiling libssh-rs v0.2.2
error[E0275]: overflow evaluating the requirement `&_ well-formed`
   --> /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lasso-0.7.2/src/util.rs:445:13
    |
445 |             $slice[$idx]
    |             ^^^^^^^^^^^^
    |
   ::: /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lasso-0.7.2/src/reader.rs:453:49
    |
453 |                 let key_string: &str = unsafe { index_unchecked!(strings, key.into_usize()) };
    |                                                 ------------------------------------------- in this macro invocation
    |
    = note: this error originates in the macro `index_unchecked` (in Nightly builds, run with -Z macro-backtrace for more info)

   Compiling termwiz v0.22.0 (https://github.com/mattwparas/wezterm.git?branch=mwp-public-scroll#e1975e65)
   Compiling async-io v2.3.2
error[E0275]: overflow evaluating the requirement `&_ well-formed`
    --> /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lasso-0.7.2/src/util.rs:445:13
     |
445  |             $slice[$idx]
     |             ^^^^^^^^^^^^
     |
    ::: /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lasso-0.7.2/src/rodeo.rs:1132:49
     |
1132 |                 let key_string: &str = unsafe { index_unchecked!(strings, key.into_usize()) };
     |                                                 ------------------------------------------- in this macro invocation
     |
     = note: this error originates in the macro `index_unchecked` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0275`.
error: could not compile `lasso` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Done!
```

**Comment by mattwparas** [comment] 2024-06-25 23:23
Thanks for opening this - looks like I just forgot to update the lock file to take the latest version of steel. I'll make them pinned to revisions more carefully in the future.

That being said I just pushed a change to this here - if you pull the latest changes and try rebuilding, I think the build will succeed this time

**Comment by mattwparas** [comment] 2024-06-25 23:34
Okay looks like I'm missing some more instructions, once we get this resolved I'll do a clean end to end install to document everything.

Can you go to where you've cloned steel, and run:

```
pushd cogs &&
cargo run -- install.scm &&
popd
```

I think I missed a step in the previous issue that you referenced.

**Comment by mattwparas** [comment] 2024-06-25 23:41
I've never seen that before - this is the lock file for steel?

**Comment by mattwparas** [comment] 2024-06-25 23:50
I'm not able to reproduce this, fresh clones of steel behave as usual, also I'd expect nuking the lock file would fix it. What version of cargo/rustc are you on?

**Comment by mattwparas** [comment] 2024-06-25 23:56
Forgive my ignorance but I don't use nix, how did you set the environment up? Could it be something with the nix file for steel?

**Comment by mattwparas** [comment] 2024-06-25 23:57
The invalid metadata error seems to be due to mixing Rust toolchains; I'm not sure how that would happen exactly

**Comment by mattwparas** [comment] 2024-06-26 00:02
Great! Let me know if there are any other weird quirks. 

Also, I think I should pick a sensible default for STEEL_HOME - I can do that tonight and just follow the same patterns that helix does, which I think is the XDG stuff. That way we can avoid that headache entirely

**Comment by mattwparas** [comment] 2024-06-26 00:09
Yeah, I agree. Right now I set mine to be `$HOME/.steel` but that was just my preference. I do install some runtime files for helix under the helix config directory, but that is subject to change moving forward - it was just an arbitrary decision to get things working

**Comment by mattwparas** [comment] 2024-06-26 00:09
> @mattwparas where would be the best place to send you rust (helix) backtraces which seem to come from one of your plugins? 😅 In the helix PR?

Can you just paste them here? A lot of people get notified on that thread

**Comment by mattwparas** [comment] 2024-06-26 00:17
Interesting, it doesn't crash for me (don't you love that)

Do you have anything open when you do this? Or is it an empty scratch buffer?

**Comment by mattwparas** [comment] 2024-06-26 00:23
Oh thats tricky isn't it, great catch! I can reproduce it

I think I should be able to protect against this

**Comment by mattwparas** [comment] 2024-06-26 00:24
I've been using this file tree for nearly a year and haven't run into that bug :smile:

**Comment by mattwparas** [comment] 2024-06-26 00:39
This is why having other uses is good!

So for context, what is happening is the file tree is getting updated, so it switches to that buffer and then does some stuff. However you're switching _from_ the existing buffer, so it marks where your selection object is, and then records that position to return to it

In this case, we're already in the buffer, so we shouldn't do that since that buffer has now been dirtied. I'll have a fix shortly

**Comment by mattwparas** [comment] 2024-06-26 00:42
Just pushed the fix - let me know if it works for you

**Comment by mattwparas** [comment] 2024-06-26 00:49
It is a good idea. Quite honestly I haven't thought about it much, I've more or less just tailored this setup to be something that works and that I'm okay with it, until I was happy enough to get the integration mature enough to merge (and also, found enough time to dedicate to getting it over the finish line).

Realistically I want every plugin to be as configurable as possible. The default choice isn't great, but it was in line with how helix has local configuration so I figured it wasn't an _awful_ choice. It is slightly annoying though, I agree, if I forget to add the .helix to a gitignore all hell breaks loose

I think it also begs the question on sandboxing / allowing plugins access to certain places or directories. I think that could help guide the direction as well.

So overall, I haven't thought much, but I think its probably worth exploring some relatively standard place to dump state

**Comment by mattwparas** [comment] 2024-06-26 01:00
No problem on the questions.

Yeah, in general it shouldn't really be possible to cause a panic in the editor. It has to do with the fact I'm using an internal API that wasn't really meant to be exposed in this form, it effectively is just indexing into the rope assuming that its long, and panics otherwise

That error is probably just in user space, so somehow I'm probably off by one in my mapping of line number -> directory (something like that). I can look into it.

With respect to having other plugins cause issues with other plugins, yes I've explored different approaches, including having every plugin exist in its own steel engine space, completely isolated from other engines. This works, but is a bit heavy resource wise compared to everything sharing. Still working on a solution though

Alternatively, if I load every plugin one by one like we're in a repl, rather than sort of doing it all at once within the init.scm, we can effectively replicate that behavior, where a plugin failing to load shouldn't stop any other plugin from running. Also, it should be relatively difficult for other plugins to affect other plugins in general so I think this solution should work well, but I have yet to explore it in depth.

**Comment by mattwparas** [comment] 2024-06-26 01:18
So with respect to designing a state system, I think in the current world it would just be guidance, to say "hey in general, please place things here" for example, but I could see a world where we add some restrictions to file system access on plugins where you could control what directories it has access to write to, in which case it could become more strict. Of course, those could be opt in / out - its all still to be decided

The error popup is just a popup I've added with steel. It is not in a final state by any means and is subject to change

**Comment by mattwparas** [comment] 2024-06-26 01:49
No worries, I appreciate the questions and ideas.

Thanks for the kind words, also glad we could get it working for you. How often does the error thing pop up for you? I'd imagine its relatively infrequent so hopefully it isn't too annoying as is.

**Comment by mattwparas** [comment] 2024-06-26 02:27
yeah, so setting that should help (or changing the theme that I've set to something you have) - if there are recurring errors popping up from a plugin, then usually it should just get fixed. I rarely if ever have any errors pop up in that window unless I've set a wrong config, so just during init, or if I'm actively developing a new plugin - in which case I'm expecting those errors to pop up

**Comment by mattwparas** [comment] 2024-06-26 02:54
The install.scm step that we missed will do all the directory creation for you, so I just need to update the instructions and xtask task to have that in there

**Closed** 2024-06-26 05:27 UTC

**Comment by mattwparas** [comment] 2024-06-26 15:55
This is also one of those situations where I haven't hardened the code for panics quite yet

**Comment by mattwparas** [comment] 2024-06-26 16:03
In `init.scm`, paste this in at around line 26:

```
(require "term.scm")
(set-default-shell! "/usr/bin/bash")
```

**Comment by mattwparas** [comment] 2024-06-26 16:10
This is subject to change, however this is the flow currently:

The `helix.scm` file is `require`'d as a module at the top level. That way the only thing that is exposed to the top level is whatever you `provide` from the `helix.scm` file.

Then, the `init.scm` file is just run plainly at the top level. So anything that you've required in the helix scm module is not available by default to the init file - its encapsulated in the helix.scm environment

**Comment by peteringram0** [comment] 2024-07-06 14:40
Sorry if this is a stupid question, im guessing i have missed a step or not setup something correctly here but i get the error:

```text
error[E02]: FreeIdentifier
      ┌─ /Users/{user}/.config/helix/helix.scm:21:8
      │
   21 │   (if (editor-doc-exists? doc-id) (editor->get-document doc-id) #f))
      │        ^^^^^^^^^^^^^^^^^^ editor-doc-exists?
```

**Comment by mattwparas** [comment] 2024-07-06 14:45
> Sorry if this is a stupid question, im guessing i have missed a step or not setup something correctly here but i get the error:
> 
> ```
> error[E02]: FreeIdentifier
>       ┌─ /Users/{user}/.config/helix/helix.scm:21:8
>       │
>    21 │   (if (editor-doc-exists? doc-id) (editor->get-document doc-id) #f))
>       │        ^^^^^^^^^^^^^^^^^^ editor-doc-exists?
> ```

What steps did you do to get this setup? There is a new xtask on the helix fork called `cargo xtask steel` that should now include everything you need.

What does the rest of your `helix.scm` look like?

**Comment by peteringram0** [comment] 2024-07-06 14:49
> > Sorry if this is a stupid question, im guessing i have missed a step or not setup something correctly here but i get the error:
> > ```
> > error[E02]: FreeIdentifier
> >       ┌─ /Users/{user}/.config/helix/helix.scm:21:8
> >       │
> >    21 │   (if (editor-doc-exists? doc-id) (editor->get-document doc-id) #f))
> >       │        ^^^^^^^^^^^^^^^^^^ editor-doc-exists?
> > ```
> 
> What steps did you do to get this setup? There is a new xtask on the helix fork called `cargo xtask steel` that should now include everything you need.
> 
> What does the rest of your `helix.scm` look like?

i ran "cargo xtask steel" (on the "steel-event-system" branch)

in my .config/helix it created the "/helix" dir. My helix.scm sits in ".config/helix/helix.scm" and is the example from this repo:


```helix.scm
(require (prefix-in helix. "helix/commands.scm"))
(require (prefix-in helix.static. "helix/static.scm"))

(provide shell git-add open-helix-scm open-init-scm)

;;@doc
;; Specialized shell implementation, where % is a wildcard for the current file
(define (shell cx . args)
  ;; Replace the % with the current file
  (define expanded (map (lambda (x) (if (equal? x "%") (current-path cx) x)) args))
  (helix.run-shell-command expanded))

;;@doc
;; Adds the current file to git	
(define (git-add cx)
  (shell cx "git" "add" "%"))


;; Functions to assist with the above
(define (editor-get-doc-if-exists doc-id)
  (if (editor-doc-exists? doc-id) (editor->get-document doc-id) #f))

(define (current-path)
  (let* ([focus (editor-focus)]
         [focus-doc-id (editor->doc-id focus)]
         [document (editor-get-doc-if-exists focus-doc-id)])

    (if document (Document-path document) #f)))

;;@doc
;; Open the helix.scm file
(define (open-helix-scm)
  (helix.open (helix.static.get-helix-scm-path)))

;;@doc
;; Opens the init.scm file
(define (open-init-scm)
  (helix.open (helix.static.get-init-scm-path)))
  
	
```

**Comment by mattwparas** [comment] 2024-07-06 14:50
Can you put this at the top?
```
(require "helix/editor.scm")
```

**Comment by mattwparas** [comment] 2024-07-06 14:51
Looks like I just missed it pasting it over into the instructions :sweat_smile:

**Comment by peteringram0** [comment] 2024-07-06 16:19
> Looks like I just missed it pasting it over into the instructions 😅

Thanks. That seems to have solved the error.
However if i add 'init.scm' with the following:

```.scm

(require-builtin steel/random as rand::)
(require (prefix-in helix. "helix/commands.scm"))
(require (prefix-in helix.static. "helix/static.scm"))

(define rng (rand::thread-rng!))

;; Picking one from the possible themes
(define possible-themes '("ayu_mirage" "tokyonight_storm" "catppuccin_macchiato"))

(define (select-random lst)
  (let ([index (rand::rng->gen-range rng 0 (length lst))]) (list-ref lst index)))

(define (randomly-pick-theme options)
  ;; Randomly select the theme from the possible themes list
  (helix.theme *helix.cx* (list (select-random options))))

(randomly-pick-theme possible-themes)
```

i get the following error:

```text
note:
            ┌─ /Users/{user}/.config/helix/helix/commands.scm:224:6
            │
        224 │     (helix.theme *helix.cx* args))
            │      ^^^^^^^^^^^


        error[E03]: TypeMismatch
            ┌─ /Users/{user}/.config/helix/helix/commands.scm:224:6
            │
        224 │     (helix.theme *helix.cx* args))
            │      ^^^^^^^^^^^ expected string, found #<steel::gc::unsafe_erased_pointers::OpaqueReference>
```

Is something missing from the config here also?

**Comment by mattwparas** [comment] 2024-07-06 16:25
Looks like another outdated instruction, sorry about that - I've pushed a fix to the `STEEL.md`.

Try changing the `randomly-pick-theme` function to this:

```scheme
(define (randomly-pick-theme options)
  ;; Randomly select the theme from the possible themes list
  (helix.theme (select-random options)))
```

**Comment by peteringram0** [comment] 2024-07-06 16:49
> Looks like another outdated instruction, sorry about that - I've pushed a fix to the `STEEL.md`.
> 
> Try changing the `randomly-pick-theme` function to this:
> 
> ```scheme
> (define (randomly-pick-theme options)
>   ;; Randomly select the theme from the possible themes list
>   (helix.theme (select-random options)))
> ```

Thats working as expected!!

Sorry for all the questions. For the file tree example: https://github.com/mattwparas/helix-config/blob/master/cogs/file-tree.scm

for the line:

```scm
(require "steel/sorting/merge-sort.scm")
```

Does this require $STEEL_HOME in path, i think i came across that in other places? If so what should be the env be?. I also see some references to 'cogs/labelled-buffers.scm' which doesnt seem to exist for me.

**Comment by mattwparas** [comment] 2024-07-06 17:15
If you installed after I updated the instructions, it should have installed stuff under $STEEL_HOME - and if you haven't set that, that should be $HOME/.steel - is there anything there?

**Comment by peteringram0** [comment] 2024-07-06 17:44
> If you installed after I updated the instructions, it should have installed stuff under $STEEL_HOME - and if you haven't set that, that should be $HOME/.steel - is there anything there?

To use the file-tree should it just be a case of adding the `/cogs` and adding a require to the `helix.scm` file? Or is there more to it? I added, doesnt error or anything but not sure the key bindings, doesnt seem to get included in any menu's or anything. Sorry this is 100% out of the scope of this from what i can see and most likely a skill issue here (after the updated instructions it all seems to work).

```helix.scm
(require "cogs/file-tree.scm")
```

**Comment by mattwparas** [comment] 2024-07-06 18:02
This is how it works now, however it is subject to change as I work on improving the keybinding API:

```scheme
# helix.scm

;;;;;;;;;;;;;;; File Tree ;;;;;;;;;;;;;;;;;

(require "cogs/file-tree.scm")

(provide fold-directory
         unfold-all-one-level
         open-file-from-picker
         create-file-tree
         create-file
         create-directory
         fold-all
         FILE-TREE
         FILE-TREE-KEYBINDINGS)

```

```scheme
# init.scm

(require (only-in "cogs/file-tree.scm" FILE-TREE-KEYBINDINGS FILE-TREE))
(require "cogs/keymaps.scm")

(define file-tree-base (deep-copy-global-keybindings))

(merge-keybindings file-tree-base FILE-TREE-KEYBINDINGS)

;; <scratch> + <doc id> is probably the best way to handle this?
(set-global-buffer-or-extension-keymap (hash  FILE-TREE file-tree-base))

```

**Comment by peteringram0** [comment] 2024-07-06 18:08
> This is how it works now, however it is subject to change as I work on improving the keybinding API:
> 
> ```scheme
> # helix.scm
> 
> ;;;;;;;;;;;;;;; File Tree ;;;;;;;;;;;;;;;;;
> 
> (require "cogs/file-tree.scm")
> 
> (provide fold-directory
>          unfold-all-one-level
>          open-file-from-picker
>          create-file-tree
>          create-file
>          create-directory
>          fold-all
>          FILE-TREE
>          FILE-TREE-KEYBINDINGS)
> ```
> 
> ```scheme
> # init.scm
> 
> (require (only-in "cogs/file-tree.scm" FILE-TREE-KEYBINDINGS FILE-TREE))
> (require "cogs/keymaps.scm")
> 
> (define file-tree-base (deep-copy-global-keybindings))
> 
> (merge-keybindings file-tree-base FILE-TREE-KEYBINDINGS)
> 
> ;; <scratch> + <doc id> is probably the best way to handle this?
> (set-global-buffer-or-extension-keymap (hash  FILE-TREE file-tree-base))
> ```

Ah i see. This is 100% out the scope of the plugin system itself and more related to that particular plugin but i get errors with the current example:

```file-tree.scm
 error[E02]: FreeIdentifier
      ┌─ /Users/{path}/.config/helix/cogs/file-tree.scm:92:36
      │
   92 │   (set! *directories* (hash-insert *directories* directory #t)))
      │                                    ^^^^^^^^^^^^^ *directories*
```

**Comment by mattwparas** [comment] 2024-07-06 18:13
Would you be able to provide more details in #3 ? I'm not able to reproduce this myself
